# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-01 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Curriculum',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('creators', models.CharField(max_length=255)),
                ('medium', models.CharField(choices=[('BK', 'Books'), ('CRS', 'Course'), ('VID', 'Videos'), ('LCT', 'Lectures'), ('WEB', 'Online Resources')], max_length=3)),
                ('image', models.ImageField(upload_to='curriculum/')),
                ('description', models.TextField()),
                ('subjects', models.ManyToManyField(to='curriculum.Curriculum')),
            ],
        ),
    ]
