# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'ordering': ['display_order'], 'verbose_name_plural': 'Curriculum'},
        ),
        migrations.AddField(
            model_name='curriculum',
            name='display_order',
            field=models.IntegerField(default=1),
        ),
    ]
