# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_auto_20170502_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='medium',
            field=models.CharField(choices=[('BK', 'Books'), ('CRS', 'Interactive Courses'), ('VID', 'Videos'), ('LCT', 'Lectures'), ('WEB', 'Online Resources')], max_length=3),
        ),
    ]
