# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_auto_20170504_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description_citation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='medium',
            field=models.CharField(choices=[('BK', 'Book'), ('CRS', 'Interactive Course'), ('VID', 'Video'), ('LCT', 'Lecture'), ('WEB', 'Online Resource')], max_length=3),
        ),
    ]
