# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_auto_20170506_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='citation_url',
            field=models.URLField(blank=True),
        ),
    ]
